services:
  mysql:
    image: mysql:8.4
    container_name: jobtracker-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: Job_Info
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uadmin -p$$MYSQL_PASSWORD --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  scraper:
    build:
      context: ./scraper-service

    container_name: jobtracker-scraper
    restart: unless-stopped

    expose:
      - "8001"

  app:
    build:
      context: .

    container_name: jobtracker-app
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy
      scraper:
        condition: service_started

    environment:
      DB_URL: jdbc:mysql://mysql:3306/Job_Info?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: admin
      SCRAPER_URL: http://scraper:8001

    ports:
      - "8080:8080"

volumes:
  mysql_data: